"""add_transactions_source_account_tx_datetime_idx

Revision ID: 31268baf1afc
Revises: 6040d304df8d
Create Date: 2026-08-21 10:26:36.727153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy    # 임베딩 컬럼 렌더링에 필요
import app.data.model.types   # 프로젝트 커스텀 타입 렌더링에 필요


# revision identifiers, used by Alembic.
revision: str = '31268baf1afc'
down_revision: Union[str, Sequence[str], None] = '6040d304df8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_acc_num_tx_dt', 'transactions', ['source_account_number', 'transaction_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acc_num_tx_dt', table_name='transactions')
    # ### end Alembic commands ###
