"""initial_schema

Revision ID: 9aad4c166342
Revises: 
Create Date: 2026-08-17 20:25:11.733073

"""
from typing import Sequence, Union

from alembic import op
import app.data.model.types
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aad4c166342'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS public")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_search")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_dashboard_insights',
    sa.Column('insight_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('chart_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index(op.f('ix_agent_dashboard_insights_created_at'), 'agent_dashboard_insights', ['created_at'], unique=False)
    op.create_table('cs_guide_documents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('fraud_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('identification_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('registration_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credit_rating', sa.SmallInteger(), nullable=False),
    sa.Column('loan_type', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_customers_gender'),
    sa.CheckConstraint("loan_type IN ('a', 'b', 'c', 'd', 'e')", name='ck_customers_loan_type'),
    sa.CheckConstraint('credit_rating BETWEEN 1 AND 9', name='ck_customers_credit_rating'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification_number')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('gcs_uri', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('documents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('fraud_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('audiences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_key')
    )
    op.create_table('fraud_rule_sets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_rule_sets_status'), 'fraud_rule_sets', ['status'], unique=False)
    op.create_index(op.f('ix_fraud_rule_sets_version'), 'fraud_rule_sets', ['version'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_balance', sa.BigInteger(), nullable=True),
    sa.Column('amount_daily_limit', sa.BigInteger(), nullable=True),
    sa.Column('indicator_openbanking', sa.Boolean(), nullable=True),
    sa.Column('suspend_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IS NULL OR account_type IN ('a', 'b', 'c', 'd', 'e')", name='ck_accounts_account_type'),
    sa.CheckConstraint('amount_daily_limit IS NULL OR amount_daily_limit >= 0', name='ck_accounts_amount_daily_limit_nonnegative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('cs_guide_document_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('cs_guide_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cs_guide_document_id'], ['cs_guide_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cs_guide_document_id', 'chunk_index', name='uq_cs_guide_document_chunks_document_id_chunk_index')
    )
    op.create_index(op.f('ix_cs_guide_document_chunks_cs_guide_document_id'), 'cs_guide_document_chunks', ['cs_guide_document_id'], unique=False)
    op.create_index('ix_cs_guide_document_chunks_embedding_hnsw', 'cs_guide_document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_id_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('fraud_rules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_set_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('type_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['fraud_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_set_id', 'type_code', name='uq_fraud_rules_rule_set_type_code')
    )
    op.create_index(op.f('ix_fraud_rules_enabled'), 'fraud_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_fraud_rules_rule_set_id'), 'fraud_rules', ['rule_set_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('dataset_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cloud_run_execution_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('mlflow_run_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_created_at'), 'training_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_runs_dataset_version_id'), 'training_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_training_runs_status'), 'training_runs', ['status'], unique=False)
    op.create_table('customer_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_number'], ['accounts.account_number'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'event_type', 'occurred_at', name='uq_customer_events_natural_key')
    )
    op.create_index(op.f('ix_customer_events_account_number'), 'customer_events', ['account_number'], unique=False)
    op.create_index('ix_customer_events_customer_id_occurred_at', 'customer_events', ['customer_id', 'occurred_at'], unique=False)
    op.create_index('ix_customer_events_event_type_occurred_at', 'customer_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('fraud_rule_components',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('component_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('condition_expression', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['fraud_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'component_key', name='uq_fraud_rule_components_rule_key')
    )
    op.create_index(op.f('ix_fraud_rule_components_rule_id'), 'fraud_rule_components', ['rule_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('source_account_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('recipient_account_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('transaction_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_amount', sa.BigInteger(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('type_general_automatic', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('access_medium', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('num_connection_failure', sa.SmallInteger(), nullable=False),
    sa.Column('initial_balance', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('operating_system', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('ip_address', postgresql.INET().with_variant(sa.String(length=45), 'sqlite'), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR().with_variant(sa.String(length=17), 'sqlite'), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('rooting_jailbreak_indicator', sa.Boolean(), nullable=False),
    sa.Column('mobile_roaming_indicator', sa.Boolean(), nullable=False),
    sa.Column('vpn_indicator', sa.Boolean(), nullable=False),
    sa.Column('flag_terminal_malicious_behavior_1', sa.Boolean(), nullable=False),
    sa.Column('flag_terminal_malicious_behavior_2', sa.Boolean(), nullable=False),
    sa.Column('flag_terminal_malicious_behavior_3', sa.Boolean(), nullable=False),
    sa.Column('flag_terminal_malicious_behavior_5', sa.Boolean(), nullable=False),
    sa.Column('flag_terminal_malicious_behavior_6', sa.Boolean(), nullable=False),
    sa.Column('transaction_status', sa.Enum('APPROVED', 'DECLINED', name='transactionstatus'), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access_medium IN ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')", name='ck_transactions_access_medium'),
    sa.CheckConstraint("channel IN ('mobile', 'internet', 'atm', 'others')", name='ck_transactions_channel'),
    sa.CheckConstraint("type_general_automatic IN ('general', 'automatic')", name='ck_transactions_type_general_automatic'),
    sa.CheckConstraint('initial_balance IS NULL OR initial_balance >= 0', name='ck_transactions_initial_balance_nonnegative'),
    sa.CheckConstraint('location_lat IS NULL OR location_lat BETWEEN -90 AND 90', name='ck_transactions_location_lat'),
    sa.CheckConstraint('location_lon IS NULL OR location_lon BETWEEN -180 AND 180', name='ck_transactions_location_lon'),
    sa.CheckConstraint('num_connection_failure >= 0', name='ck_transactions_num_connection_failure'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_account_number'], ['accounts.account_number'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_number'], ['accounts.account_number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_customer_id_transaction_datetime', 'transactions', ['customer_id', 'transaction_datetime'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_account_number'), 'transactions', ['recipient_account_number'], unique=False)
    op.create_index(op.f('ix_transactions_source_account_number'), 'transactions', ['source_account_number'], unique=False)
    op.create_index('ix_transactions_transaction_datetime', 'transactions', ['transaction_datetime'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_older', sa.Boolean(), nullable=False),
    sa.Column('top_fraud_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('question_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('URL_SENT', 'IN_PROGRESS', 'HANDOFF_REQUESTED', 'DONE', 'FAILED')", name='ck_chat_sessions_status'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_session_id'),
    sa.UniqueConstraint('transaction_id', name='uq_chat_sessions_transaction_id')
    )
    op.create_index('ix_chat_sessions_status', 'chat_sessions', ['status'], unique=False)
    op.create_table('derived_features',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('time_difference', sa.Interval().with_variant(app.data.model.types.SQLiteIntervalSeconds(), 'sqlite'), nullable=False),
    sa.Column('one_month_max_amount', sa.BigInteger(), nullable=False),
    sa.Column('one_month_std_dev', sa.Float(), nullable=False),
    sa.Column('dawn_one_month_max_amount', sa.BigInteger(), nullable=False),
    sa.Column('dawn_one_month_std_dev', sa.Float(), nullable=False),
    sa.Column('unused_terminal_status', sa.Boolean(), nullable=False),
    sa.Column('unused_account_status', sa.Boolean(), nullable=False),
    sa.Column('transaction_history_with_the_account', sa.Integer(), nullable=False),
    sa.Column('flag_deposit_more_than_ten_million', sa.Boolean(), nullable=False),
    sa.Column('number_of_transaction_with_the_account', sa.Integer(), nullable=False),
    sa.Column('last_atm_transaction_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bank_branch_transaction_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_change_of_authentication_1', sa.Boolean(), nullable=False),
    sa.Column('flag_change_of_authentication_2', sa.Boolean(), nullable=False),
    sa.Column('flag_change_of_authentication_3', sa.Boolean(), nullable=False),
    sa.Column('flag_change_of_authentication_4', sa.Boolean(), nullable=False),
    sa.Column('inquiry_atm_limit', sa.Boolean(), nullable=False),
    sa.Column('increase_atm_limit', sa.Boolean(), nullable=False),
    sa.Column('release_suspension', sa.Boolean(), nullable=False),
    sa.Column('recipient_transaction_resumed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_account_suspend_status', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dawn_one_month_max_amount >= 0', name='ck_derived_features_dawn_max_nonnegative'),
    sa.CheckConstraint('dawn_one_month_std_dev >= 0', name='ck_derived_features_dawn_std_nonnegative'),
    sa.CheckConstraint('distance >= 0', name='ck_derived_features_distance_nonnegative'),
    sa.CheckConstraint('number_of_transaction_with_the_account >= 0', name='ck_derived_features_recent_count_nonnegative'),
    sa.CheckConstraint('one_month_max_amount >= 0', name='ck_derived_features_month_max_nonnegative'),
    sa.CheckConstraint('one_month_std_dev >= 0', name='ck_derived_features_month_std_nonnegative'),
    sa.CheckConstraint('transaction_history_with_the_account >= 0', name='ck_derived_features_history_count_nonnegative'),
    sa.ForeignKeyConstraint(['id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_type_score_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_set_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_filter_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('primary_fraud_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('type_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('matched_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("rule_filter_status IN ('APPLIED', 'SKIPPED_NOT_FRAUD', 'FAILED')", name='ck_fraud_type_score_results_filter_status'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['fraud_rule_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_fraud_type_score_results_transaction_id')
    )
    op.create_index(op.f('ix_fraud_type_score_results_created_at'), 'fraud_type_score_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_type_score_results_primary_fraud_type'), 'fraud_type_score_results', ['primary_fraud_type'], unique=False)
    op.create_index(op.f('ix_fraud_type_score_results_rule_set_id'), 'fraud_type_score_results', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_fraud_type_score_results_transaction_id'), 'fraud_type_score_results', ['transaction_id'], unique=False)
    op.create_table('ml_prediction_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('predict_result', sa.Boolean(), nullable=False),
    sa.Column('predict_proba', sa.Float(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_prediction_results_created_at'), 'ml_prediction_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_prediction_results_transaction_id'), 'ml_prediction_results', ['transaction_id'], unique=False)
    op.create_table('transaction_labels',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('confirmed_is_fraud', sa.Boolean(), nullable=False),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('agent_cases',
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fraud_type_score_result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('execution_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_grade', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('investigation_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('best_similar_case_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('similar_case_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generation_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("execution_status IN ('PROCESSING', 'COMPLETED', 'FAILED')", name='ck_agent_cases_execution_status'),
    sa.CheckConstraint("risk_grade IN ('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH')", name='ck_agent_cases_risk_grade'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='ck_agent_cases_risk_score'),
    sa.ForeignKeyConstraint(['best_similar_case_id'], ['agent_cases.case_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fraud_type_score_result_id'], ['fraud_type_score_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('fraud_type_score_result_id', name='uq_agent_cases_fraud_type_score_result_id'),
    sa.UniqueConstraint('transaction_id', name='uq_agent_cases_transaction_id')
    )
    op.create_index('ix_agent_cases_execution_status_created_at', 'agent_cases', ['execution_status', 'created_at'], unique=False)
    op.create_index('ix_agent_cases_risk_grade', 'agent_cases', ['risk_grade'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sender_type IN ('AI', 'HUMAN', 'SYSTEM')", name='ck_chat_messages_sender_type'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_chat_messages_session_sent_at', 'chat_messages', ['chat_session_id', 'sent_at'], unique=False)
    op.create_table('fraud_type_score_after_chat',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('type_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('agent_reviews',
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('confirmed_fraud_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('performed_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('checklist_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['agent_cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('chat_answers',
    sa.Column('answer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('question_step', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quality_verdict', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('verdict_skip_reason', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
    sa.Column('is_adopted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("quality_verdict IS NULL OR quality_verdict IN ('SUFFICIENT', 'TOO_VAGUE', 'WANT_END')", name='ck_chat_answers_quality_verdict'),
    sa.CheckConstraint("verdict_skip_reason IS NULL OR verdict_skip_reason IN ('MAX_RETRY_EXCEEDED', 'EVALUATOR_FAILED')", name='ck_chat_answers_verdict_skip_reason'),
    sa.CheckConstraint('attempt_no BETWEEN 1 AND 3', name='ck_chat_answers_attempt_no'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('chat_session_id', 'question_step', 'attempt_no', name='uq_chat_answers_session_step_attempt'),
    sa.UniqueConstraint('message_id', name='uq_chat_answers_message_id')
    )
    op.create_index('ix_chat_answers_session_step', 'chat_answers', ['chat_session_id', 'question_step'], unique=False)
    op.create_index('uq_chat_answers_adopted', 'chat_answers', ['chat_session_id', 'question_step'], unique=True, postgresql_where=sa.text('is_adopted'), sqlite_where=sa.text('is_adopted = 1'))
    op.create_table('chat_fraud_circumstances',
    sa.Column('circumstance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('circumstance_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source_answer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_answer_id'], ['chat_answers.answer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('circumstance_id'),
    sa.UniqueConstraint('chat_session_id', 'circumstance_code', name='uq_chat_fraud_circumstances_session_code')
    )
    op.create_table('chat_guide_search_queries',
    sa.Column('guide_search_query_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source_answer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 5', name='ck_chat_guide_search_queries_position'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_answer_id'], ['chat_answers.answer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guide_search_query_id'),
    sa.UniqueConstraint('source_answer_id', 'position', name='uq_chat_guide_search_queries_answer_position')
    )
    op.create_foreign_key(
        'fk_chat_sessions_last_message_id',
        'chat_sessions',
        'chat_messages',
        ['last_message_id'],
        ['message_id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_sessions_last_message_id', 'chat_sessions', type_='foreignkey')
    op.drop_table('chat_guide_search_queries')
    op.drop_table('chat_fraud_circumstances')
    op.drop_index('uq_chat_answers_adopted', table_name='chat_answers', postgresql_where=sa.text('is_adopted'), sqlite_where=sa.text('is_adopted = 1'))
    op.drop_index('ix_chat_answers_session_step', table_name='chat_answers')
    op.drop_table('chat_answers')
    op.drop_table('agent_reviews')
    op.drop_table('fraud_type_score_after_chat')
    op.drop_index('ix_chat_messages_session_sent_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_agent_cases_risk_grade', table_name='agent_cases')
    op.drop_index('ix_agent_cases_execution_status_created_at', table_name='agent_cases')
    op.drop_table('agent_cases')
    op.drop_table('transaction_labels')
    op.drop_index(op.f('ix_ml_prediction_results_transaction_id'), table_name='ml_prediction_results')
    op.drop_index(op.f('ix_ml_prediction_results_created_at'), table_name='ml_prediction_results')
    op.drop_table('ml_prediction_results')
    op.drop_index(op.f('ix_fraud_type_score_results_transaction_id'), table_name='fraud_type_score_results')
    op.drop_index(op.f('ix_fraud_type_score_results_rule_set_id'), table_name='fraud_type_score_results')
    op.drop_index(op.f('ix_fraud_type_score_results_primary_fraud_type'), table_name='fraud_type_score_results')
    op.drop_index(op.f('ix_fraud_type_score_results_created_at'), table_name='fraud_type_score_results')
    op.drop_table('fraud_type_score_results')
    op.drop_table('derived_features')
    op.drop_index('ix_chat_sessions_status', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_transactions_transaction_datetime', table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_account_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_account_number'), table_name='transactions')
    op.drop_index('ix_transactions_customer_id_transaction_datetime', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fraud_rule_components_rule_id'), table_name='fraud_rule_components')
    op.drop_table('fraud_rule_components')
    op.drop_index('ix_customer_events_event_type_occurred_at', table_name='customer_events')
    op.drop_index('ix_customer_events_customer_id_occurred_at', table_name='customer_events')
    op.drop_index(op.f('ix_customer_events_account_number'), table_name='customer_events')
    op.drop_table('customer_events')
    op.drop_index(op.f('ix_training_runs_status'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_dataset_version_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_created_at'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_fraud_rules_rule_set_id'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_enabled'), table_name='fraud_rules')
    op.drop_table('fraud_rules')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_cs_guide_document_chunks_embedding_hnsw', table_name='cs_guide_document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_cs_guide_document_chunks_cs_guide_document_id'), table_name='cs_guide_document_chunks')
    op.drop_table('cs_guide_document_chunks')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_fraud_rule_sets_version'), table_name='fraud_rule_sets')
    op.drop_index(op.f('ix_fraud_rule_sets_status'), table_name='fraud_rule_sets')
    op.drop_table('fraud_rule_sets')
    op.drop_table('documents')
    op.drop_table('dataset_versions')
    op.drop_table('customers')
    op.drop_table('cs_guide_documents')
    op.drop_index(op.f('ix_agent_dashboard_insights_created_at'), table_name='agent_dashboard_insights')
    op.drop_table('agent_dashboard_insights')
    # ### end Alembic commands ###
